# Generated by Django 4.2 on 2025-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('clues', models.JSONField(default=list)),
                ('fun_fact', models.TextField(blank=True)),
                ('trivia', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
